# Generated by Django 4.0.2 on 2022-03-26 01:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStation',
            fields=[
                ('sto_name', models.CharField(help_text='Название станции тех. обслуживания', max_length=30, verbose_name='Название')),
                ('sto_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('location', models.CharField(help_text='Адрес станции тех. обслуживания', max_length=150, verbose_name='Адрес')),
                ('location_coordinates', models.CharField(default='', help_text='Координаты станции тех. обслуживания', max_length=150, verbose_name='Коордиаты адреса')),
                ('description_sto', models.CharField(help_text='Описание деятельности СТО', max_length=150, verbose_name='Описание СТО')),
                ('about_sto', models.TextField(default='', help_text='Полное описание деятельности СТО', max_length=3000, verbose_name='Описание СТО')),
            ],
            options={
                'verbose_name': 'Станция тех. обслуживания',
                'verbose_name_plural': 'Станции тех. обслуживаний',
            },
        ),
        migrations.CreateModel(
            name='ServiceSTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название услуги')),
                ('service_check', models.IntegerField(default=0, help_text='Стоимость услуги в рублях', verbose_name='Стоимость услуги')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.servicestation', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_sto', models.ImageField(help_text='Выберите изображение', upload_to='', verbose_name='Изображения')),
                ('order', models.IntegerField(default=1, help_text='Порядковый номер создается автоматически', verbose_name='Порядковый номер')),
                ('sto_id_image', models.ForeignKey(default='Станция тех. обслуживания', help_text='Выберите СТО', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.servicestation', verbose_name='Изображение СТО')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(help_text='Оставьте отзыв о СТО', max_length=1000, verbose_name='Отзыв')),
                ('user_name', models.CharField(help_text='Напишите выдуманное имя для отзыва', max_length=25, verbose_name='Имя пользователя')),
                ('stars', models.IntegerField(help_text='Оценка ресторана по 5 бальной шкале', verbose_name='Оценка')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата создается автоматически', verbose_name='Дата')),
                ('order', models.IntegerField(default=9999, help_text='Порядковый номер создается автоматически', verbose_name='Порядковый номер')),
                ('id_service_station', models.ForeignKey(help_text='Выберите СТО', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mainapp.servicestation', verbose_name='Для какого СТО')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-order',),
                'unique_together': {('id_service_station', 'order')},
            },
        ),
    ]
